### ISSUE TITLE
SYSVOL FRS Migration false positive

### ISSUE THREAD

**Issue by ld0614** [netwrix/pingcastle#265]
On my domain I'm seeing the rule A-NTFRSOnSysvol trigger

However when running the microsoft recommended validation for sysvol migration it returns that FRS is in the eliminated state

![image](https://github.com/user-attachments/assets/be6b8058-6327-4a0a-8cbe-e56746583485)

Reading the explication text it appears that any container under CN=Domain System Volume (SYSVOL share),CN=File Replication Service,CN=System will trigger this alert. Looking under that container we have 2 sub containers, neither appear to be related to our current domain and haven't been updated in nearly 10 years. Neither of these objects have server references or any sub objects. with ntfrsutl erroring on every command. My guess is that these relate to old domains which no longer exist

![image](https://github.com/user-attachments/assets/2d17baa9-cf5a-42fe-91d6-24bdaecf5fdd)

Would it be possible to either have a more specific check for the domain SYSVOL migration and/or provide greater information relating to clearing our of these old objects if they are an issue?

**Comment by An-dir** [comment]
Did you run `dfsrmig /getglobalstate` on your PDC Emulator as well? Check this result, as it might tell you that it is not fully finished.

**Comment by JoeDibley** [comment]
My understanding is that the DFSR Migration tool should remove these settings when doing the migration. It may be possible these were orphaned domain controllers when the migration happened and these were left behind or maybe some RODCs that got stuck in the eliminating phase? 

Its worth checking An-dir's above recommendation as this should tell you any issues.

**Comment by ld0614** [comment]
> Did you run `dfsrmig /getglobalstate` on your PDC Emulator as well? Check this result, as it might tell you that it is not fully finished.

Thanks for the suggestion, I went back and validated the FSMO roles, the screenshot above is actually from the DC running PDC Emulator

**Comment by An-dir** [comment]
Don' t miss the difference between `dfsrmig /getglobalstate` and `dfsrmig /getmigrationstate`. Check both!

**Comment by ld0614** [comment]
My apologies, I had missed that you'd asked for a different command. Unfortunately it just confirms that as far as AD is concerned FRS is eliminated 
![image](https://github.com/user-attachments/assets/9d626fa0-c295-41f1-8d9e-18c21a015720)

**Comment by An-dir** [comment]
As knowing your environment ist the key to make the right decisions, I would not make further suggestions at that point. There are possible states that would make the current setup fragile and it might collaps on changing something (like restores after/while migrating from FRS).

What I can say, make sure your whole environment (DCs) is dfsr compatible and validate that you have a backup and a proper desaster recovery procedure before proceeding. 
Metadata cleanup might be something you could read in further, because as joe mentioned there might be some parts of old DCs leftover.
As this does NOT seem to be a PingCastle issue, I would suggest to stay in contact with any MS supporting parties.

**Comment by ld0614** [comment]
Thanks for you input. I'll close the issue now and will see what MS Support have to say
